databases:
  - name: pizza
    databaseName: pizza
    user: pizza
    ipAllowList: []

services:
  - type: web
    name: pizza
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pizza
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
    ipAllowList: []
    plan: free   
    maxmemoryPolicy: noeviction